### ISSUE TITLE
Using Hyprland with elogind

### ISSUE THREAD

**Issue by threddast** [rakino/Rosenthal#2]
Do you know if it's possible to get hyprland to work with elogind? I tried replacing "libseat-sans-logind" with normal libseat but still Hyprland would fail if using elogind instead of seatd.

Thank you for making this channel public!

**Comment by rakino** [comment]
@threddast As `hyprland` depends on `wlroots-dev`, which in turn inherits from `wlroots-0.16.0`, have you tried to remove [this line](https://github.com/rakino/Rosenthal/blob/trunk/rosenthal/packages/wm.scm#L58)?

I can build and run Hyprland with above change. However I don't know whether it works for elogind.

**Comment by rakino** [comment]
If you are using Rosenthal as a Guix channel, you can change the `branch` field from `trunk` to `2-wlroots-logind`, then invoking `guix pull`, build the new `hyprland` and see whether the issue is addressed.

**Comment by threddast** [comment]
Thank you, it works now!

**Comment by rakino** [comment]
I've pushed the change to trunk as c78aa9023226f63b110a5d833810416687559cfd. If you are using the Guix channel, you can now change back the `branch` field, and invoke `guix pull` with the `--allow-downgrades` option. Thank you for reporting the issue!
