### ISSUE TITLE
Merge with nonguix

### ISSUE THREAD

**Issue by arkhan** [rakino/Rosenthal#4]
Greetings, great work with Linux-Xanmod, but there is some possibility of joining this project with Nonguix.

Thanks

**Comment by rakino** [comment]
Thank you for the proposal!  

Actually I already have a plan to contribute package definitions of both `linux-hardened` and `linux-xanmod` to Nonguix, though that may take a while to begin...

**Comment by rakino** [comment]
https://gitlab.com/nonguix/nonguix/-/merge_requests/260

**Comment by arkhan** [comment]
Thanks
