### ISSUE TITLE
Upstream emacs-xonsh-mode

### ISSUE THREAD

**Issue by jgarte** [rakino/Rosenthal#8]
Hi,

If ready, would you be able to upstream [emacs-xonsh-mode](https://toys.whereis.みんな/?search=emacs-xonsh-mode)?

Let me know if you need any help with that.

**Comment by rakino** [comment]
https://git.savannah.gnu.org/cgit/guix.git/commit/?id=af3daff5ea27837193b968b2a42725fcac586b5f
